remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Toolbox
description: A toolbox for academia and non-academia people to get in touch with various methods for uncertainty quantification in machine learning.

show_downloads: true
google_analytics:
theme: jekyll-theme-dinky
markdown: kramdown
layout: default
comments: true
